# language: node_js
# node_js:
#  — “7”
# script:
#  — echo “Deploy!!”
# install:
#  — npm install -g firebase-tools
# after_success:
#  — firebase deploy — project assist-hr — token $FIREBASE_TOKEN.


# tavis.yml

language: node_js
node_js:
  - "7"

branches:
  only:
  - master

before_script:
  - npm install -g  firebase-tools
  - npm install -g  @angular/cli
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --prod && npm run deploy; fi

  after_success:
   - firebase deploy --token $FIREBASE_TOKEN

# deploy:
#   - provider: firebase
#     token:
#       secure: token
#     project: "assist-hr"
#     on:
#       branch: master