language: node_js

node_js:
  - '10'
  - '9'
  - '8'
  - node

script: -npm run checkNode
  - npm run checkNode

after_success:
  - test $TRAVIS_BRANCH = "master" # firebase deploy after angular-cli build

